USE `pilot_fish`;

CREATE TABLE `POLISEAHOLDERS` (
    `FNAME` VARCHAR(50) NOT NULL,
    `LNAME` VARCHAR(50) NOT NULL,
    `AGE` INT NOT NULL,
    `HOME_OCEAN` VARCHAR(50) NOT NULL,
    `HOME_REEF` VARCHAR(50) NOT NULL,
    `HOME_DEPTH_METERS` DECIMAL NOT NULL
);
